"""
Report Service — Generates professional survey PDF reports using ReportLab.
"""
import io
import logging
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, ListFlowable, ListItem,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY

logger = logging.getLogger("geomind.reports")

# Colors matching the app design
BRAND = HexColor("#6366f1")
BRAND_LIGHT = HexColor("#818cf8")
DARK_BG = HexColor("#0f172a")
DARK_CARD = HexColor("#1e293b")
TEXT_PRIMARY = HexColor("#e2e8f0")
TEXT_SECONDARY = HexColor("#94a3b8")
ACCENT_RED = HexColor("#ef4444")
ACCENT_GREEN = HexColor("#22c55e")
ACCENT_BLUE = HexColor("#3b82f6")


def generate_report_pdf(
    report_type: str,
    title: str,
    file_data: list[dict],
    template: dict | None = None,
    user: dict | None = None,
) -> bytes:
    """Generate a professional PDF report and return bytes."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"],
        fontSize=24, textColor=BRAND, spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=TEXT_SECONDARY, spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "ReportHeading", parent=styles["Heading2"],
        fontSize=14, textColor=BRAND, spaceBefore=16, spaceAfter=8,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "ReportBody", parent=styles["Normal"],
        fontSize=10, textColor=TEXT_PRIMARY, leading=15,
        spaceAfter=6, alignment=TA_JUSTIFY,
    )
    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=8, textColor=TEXT_SECONDARY,
    )
    value_style = ParagraphStyle(
        "Value", parent=styles["Normal"],
        fontSize=10, textColor=TEXT_PRIMARY, fontName="Helvetica-Bold",
    )
    warning_style = ParagraphStyle(
        "Warning", parent=styles["Normal"],
        fontSize=9, textColor=ACCENT_RED,
    )
    insight_style = ParagraphStyle(
        "Insight", parent=styles["Normal"],
        fontSize=9, textColor=ACCENT_GREEN,
    )

    elements = []

    # ─── Header ───
    elements.append(Paragraph(f"<b>{title}</b>", title_style))
    elements.append(Paragraph(
        f"Generated by GeoMind AI | {datetime.now().strftime('%B %d, %Y')} | Report Type: {report_type.upper()}",
        subtitle_style,
    ))

    # Separator line
    from reportlab.platypus import HRFlowable
    elements.append(HRFlowable(width="100%", thickness=1, color=BRAND, spaceAfter=14))

    # ─── Executive Summary ───
    elements.append(Paragraph("Executive Summary", heading_style))
    all_warnings = []
    all_insights = []
    all_actions = []

    for fd in file_data:
        w = fd.get("warnings") or []
        i = fd.get("insights") or []
        a = fd.get("next_actions") or []
        all_warnings.extend(w if isinstance(w, list) else [])
        all_insights.extend(i if isinstance(i, list) else [])
        all_actions.extend(a if isinstance(a, list) else [])

    summary_parts = [f"This report summarizes <b>{len(file_data)}</b> analyzed survey file(s)."]
    if all_warnings:
        summary_parts.append(f"Detected <b>{len(all_warnings)}</b> anomalies requiring attention.")
    if all_insights:
        summary_parts.append(f"Generated <b>{len(all_insights)}</b> engineering insights.")
    if all_actions:
        summary_parts.append(f"Suggested <b>{len(all_actions)}</b> recommended next actions.")

    elements.append(Paragraph(" ".join(summary_parts), body_style))
    elements.append(Spacer(1, 10))

    # ─── Project Information ───
    elements.append(Paragraph("Project Information", heading_style))
    info_data = []
    if user:
        info_data.append(["Surveyor", user.get("email", "N/A")])
    info_data.append(["Report Date", datetime.now().strftime("%Y-%m-%d %H:%M")])
    info_data.append(["Report Type", report_type.upper()])
    info_data.append(["Files Analyzed", str(len(file_data))])

    info_table = Table(
        [[Paragraph(k, label_style), Paragraph(v, value_style)] for k, v in info_data],
        colWidths=[1.5 * inch, 4 * inch],
    )
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), DARK_CARD),
        ("TEXTCOLOR", (0, 0), (-1, -1), TEXT_PRIMARY),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [DARK_CARD, DARK_BG]),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 12))

    # ─── File Details ───
    for i, fd in enumerate(file_data):
        elements.append(Paragraph(f"File {i + 1}: {fd.get('file_id', 'unknown')}", heading_style))

        summary = fd.get("summary", "")
        if summary:
            elements.append(Paragraph(f"<b>Summary:</b> {summary}", body_style))

        # Warnings
        warnings = fd.get("warnings") or []
        if warnings:
            elements.append(Paragraph("<b>Detected Anomalies:</b>", body_style))
            for w in warnings[:5]:
                elements.append(Paragraph(f"• <font color='#ef4444'>{w}</font>", warning_style))

        # Insights
        insights = fd.get("insights") or []
        if insights:
            elements.append(Paragraph("<b>Engineering Insights:</b>", body_style))
            for ins in insights[:5]:
                elements.append(Paragraph(f"• <font color='#22c55e'>{ins}</font>", insight_style))

        elements.append(Spacer(1, 8))

    # ─── Aggregated Summary ───
    if all_warnings:
        elements.append(PageBreak())
        elements.append(Paragraph("All Detected Anomalies", heading_style))
        for w in all_warnings:
            elements.append(Paragraph(f"• {w}", warning_style))
        elements.append(Spacer(1, 10))

    if all_insights:
        elements.append(Paragraph("All Engineering Insights", heading_style))
        for ins in all_insights:
            elements.append(Paragraph(f"• {ins}", insight_style))
        elements.append(Spacer(1, 10))

    if all_actions:
        elements.append(Paragraph("Recommended Next Actions", heading_style))
        for a in all_actions:
            elements.append(Paragraph(f"→ {a}", body_style))
        elements.append(Spacer(1, 10))

    # ─── Footer ───
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=grey, spaceAfter=6))
    elements.append(Paragraph(
        "<i>This report was automatically generated by GeoMind AI. "
        "All results should be reviewed by a licensed Professional Surveyor "
        "before being used for legal or engineering decisions.</i>",
        ParagraphStyle("Footer", parent=styles["Normal"],
                       fontSize=7, textColor=grey, alignment=TA_CENTER)
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()